### ISSUE TITLE
Absent 'To:' header causes exception and message to DLQ

### ISSUE THREAD

**Issue by BAPostma** [BAPostma/Loft#2]
Incoming messages that lack a `To:` header (e.g. `To: undisclosed receipients;`) are placed in the right S3 bucket but not synced via email. An exception is raised and the notification is DLQ'd. It seems the bucket is inferred from SES metadata whereas data for the database is taken from the email message headers.

```
Value cannot be null. (Parameter 'source'): ArgumentNullException
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at Loft.Function.Models.DynamoDB.EmailMessage..ctor(SimpleEmailService`1 message) in /home/runner/work/Loft/Loft/src/Loft.Function/Models/DynamoDB/EmailMessage.cs:line 45
   at Loft.Function.Handlers.DynamoStorageHandler.Handle(SimpleEmailService`1 message, ILambdaContext context) in /home/runner/work/Loft/Loft/src/Loft.Function/Handlers/DynamoStorageHandler.cs:line 32
   at Loft.Function.Handlers.HandlerBase.Next(SimpleEmailService`1 message, ILambdaContext context) in /home/runner/work/Loft/Loft/src/Loft.Function/Handlers/HandlerBase.cs:line 20
   at Loft.Function.Handlers.S3ArchiveHandler.Handle(SimpleEmailService`1 message, ILambdaContext context) in /home/runner/work/Loft/Loft/src/Loft.Function/Handlers/S3ArchiveHandler.cs:line 39
   at Loft.Function.Handlers.HandlerBase.Next(SimpleEmailService`1 message, ILambdaContext context) in /home/runner/work/Loft/Loft/src/Loft.Function/Handlers/HandlerBase.cs:line 20
   at Loft.Function.Handlers.CloudWatchLogHandler.Handle(SimpleEmailService`1 message, ILambdaContext context) in /home/runner/work/Loft/Loft/src/Loft.Function/Handlers/CloudWatchLogHandler.cs:line 19
   at Loft.Function.LambdaFunction.FunctionHandler(SQSEvent sqsEvent, ILambdaContext context) in /home/runner/work/Loft/Loft/src/Loft.Function/LambdaFunction.cs:line 71
   at lambda_method(Closure , Stream , Stream , LambdaContextInternal )
```

**Comment by BAPostma** [comment]
This issue has been fixed in commit 783197d.
